# Version 3.0
services:
  nordpool-backend:
    build:
      context: .
      dockerfile: Dockerfile.nordpool
    volumes:
      - ./data:/app/data
    ports:
      - "8000:8000"

  wifi-backend:
    build:
      context: .
      dockerfile: Dockerfile.wifi
    volumes:
      - ./data:/app/data
    ports:
      - "8001:8001"

  nordpool-frontend:
    image: nginx:alpine
    volumes:
      - ./nordpool/frontend:/usr/share/nginx/html:ro
    ports:
      - "8080:80"

  wifi-frontend:
    image: nginx:alpine
    volumes:
      - ./wifi_detector/frontend:/usr/share/nginx/html:ro
    ports:
      - "8081:80"
